version: '3.2'

networks:
  integration-test-example:

services:
  it_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - .:/go/src/target
    ports:
      - 2565:2565  
    depends_on:
      - db
    networks:
      - integration-test-example
  db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: assessment
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test-example
    